version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    env_file:
      - .env
    volumes:
      - app

volumes:
  app: