version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db # specify the absolute path inside the container
    networks:
      - discount-hub-network

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - discount-hub-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    depends_on:
    - mongo
    - redis

networks:
  discount-hub-network:
    driver: bridge

volumes:
  db: