version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db # specify the absolute path inside the container
    networks:
      - discount-hub-network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - discount-hub-network

networks:
  discount-hub-network:
    driver: bridge

volumes:
  db: