name: Deploy To Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            echo "Deploying to Digital Ocean..."
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2 @swc/core @nestjs/cli

            apt-get update \
            && apt-get install -y chromium \
            fonts-freefont-ttf \
            fonts-indic \
            fonts-noto-color-emoji \
            fonts-noto-cjk \
            fonts-ipafont-gothic \
            fonts-wqy-zenhei \
            fonts-thai-tlwg \
            fonts-kacst \
            libxss1 \
            --no-install-recommends \
            && rm -rf /var/lib/apt/lists/*

            cd giitsc/discount-hub-api-v2
            git checkout main
            git pull
            echo "${{ vars.PRODUCTION_VARIABLES }}" > .env
            npm install
            npm run build
            pm2 start ecosystem.config.js --env production
            exit
