name: Deploy To Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Deploying to Digital Ocean..."
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2 @swc/core @nestjs/cli

            apt-get update \
            && apt-get install -y google-chrome-stable \
            fonts-freefont-ttf \
            fonts-indic \
            fonts-noto-color-emoji \
            fonts-noto-cjk \
            fonts-ipafont-gothic \
            fonts-wqy-zenhei \
            fonts-thai-tlwg \
            fonts-kacst \
            libxss1 \
            --no-install-recommends \
            && rm -rf /var/lib/apt/lists/*

            cd giitsc/discount-hub-api-v2
            git checkout main
            git pull
            echo "${{ vars.PRODUCTION_VARIABLES }}" > .env


            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build
            docker exec ollama ollama pull llama3.2

            npm install
            npx puppeteer browsers install chrome
            npm run build
            pm2 start ecosystem.config.js --env production
            exit
