name: Deploy To Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          script: |
            docker system prune --force
            cd giitsc/discount-hub-api-v2
            git checkout main
            git pull
            echo "${{ vars.PRODUCTION_VARIABLES }}" > .env
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up --build -d
            exit
